# Generated by Django 5.2.7 on 2025-12-26 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_remove_feedcomment_feed_remove_feedlike_feed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='community.communitycategory'),
        ),
    ]
