# Generated by Django 5.2.7 on 2025-12-25 15:51

import users.utils.generate_username
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, default=users.utils.generate_username.generate_username, max_length=100, null=True, unique=True),
        ),
    ]
