# Generated by Django 5.2.7 on 2025-12-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspaceinvitation',
            name='invite_code',
        ),
        migrations.RemoveField(
            model_name='workspaceinvitation',
            name='max_uses',
        ),
        migrations.RemoveField(
            model_name='workspaceinvitation',
            name='uses',
        ),
    ]
