# Generated by Django 6.0.5 on 2026-05-27 12:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspaceinvitation',
            name='invite_code',
        ),
        migrations.RemoveField(
            model_name='workspaceinvitation',
            name='max_uses',
        ),
        migrations.RemoveField(
            model_name='workspaceinvitation',
            name='uses',
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public (Visible to Workspace)'), ('private', 'Private (Invite Only)')], default='private', max_length=10),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('create_project', 'Created Project'), ('add_project_member', 'Added Project Member'), ('create_task', 'Created Task'), ('start_task', 'Started Task'), ('complete_task', 'Completed Task'), ('comment', 'Commented')], max_length=20)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workspace.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
