# Generated by Django 6.0.7 on 2026-07-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_remove_workspaceinvitation_invite_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('invite', 'Invite Only'), ('public', 'Public')], default='private', max_length=10),
        ),
    ]
