# Generated by Django 5.2.7 on 2025-12-24 13:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_remove_workspaceinvitation_invite_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('create_project', 'Created Project'), ('create_task', 'Created Task'), ('complete_task', 'Completed Task'), ('join_workspace', 'Joined Workspace'), ('comment', 'Commented')], max_length=20)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workspace.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
