# Generated by Django 5.2.7 on 2025-12-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public (Visible to Workspace)'), ('private', 'Private (Invite Only)')], default='private', max_length=10),
        ),
    ]
