# Generated by Django 6.0.7 on 2026-07-26 14:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_workspace_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='visibility',
        ),
        migrations.CreateModel(
            name='WorkspaceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='workspace_documents/')),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Document'), ('spreadsheet', 'Spreadsheet'), ('image', 'Image'), ('presentation', 'Presentation'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public (All Workspace Members)'), ('private', 'Private (Uploader & Admins Only)')], default='public', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
