# Generated by Django 5.2.7 on 2025-12-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_project_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('create_project', 'Created Project'), ('add_project_member', 'Added Project Member'), ('create_task', 'Created Task'), ('start_task', 'Started Task'), ('complete_task', 'Completed Task'), ('comment', 'Commented')], max_length=20),
        ),
    ]
